import { createRoot } from "react-dom/client";
import { Amplify } from "aws-amplify";
import App from "./App";
import "./index.css";

// Import Amplify outputs (will be generated by Amplify)
// In development, this file might not exist yet
let amplifyConfig = {};
try {
  amplifyConfig = (await import("../../amplify_outputs.json")).default;
} catch (error) {
  console.log("Amplify outputs not found - running without backend");
}

Amplify.configure(amplifyConfig);

createRoot(document.getElementById("root")!).render(<App />);
