import { createRoot } from "react-dom/client";
import { Amplify } from "aws-amplify";
import App from "./App";
import "./index.css";

// Import Amplify outputs (generated by Amplify backend)
try {
  const outputs = await import("../../amplify_outputs.json");
  Amplify.configure(outputs.default);
  console.log("✅ Amplify configured with backend");
} catch (error) {
  console.log("⚠️ Amplify outputs not found - running without backend connection");
}

createRoot(document.getElementById("root")!).render(<App />);
