name: prevent-direct-push

on:
  push:
    branches: [ main ]

jobs:
  block-direct-push:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Fail if commit not from GitHub merge bot
        uses: actions/github-script@v7
        with:
          script: |
            const actor = context.actor
            // Allow pushes only from web-flow (merge commits) or dependabot
            const allowed = new Set(['web-flow', 'dependabot[bot]'])
            if (!allowed.has(actor)) {
              core.setFailed(`Direct pushes to main are blocked. Actor: ${actor}`)
            }

